# Generated by Django 5.0.1 on 2025-10-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('versione', models.CharField(max_length=20)),
                ('produttore', models.CharField(max_length=100)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gratuito', models.BooleanField(default=False)),
                ('data_rilascio', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Software',
            },
        ),
    ]
