# Generated by Django 5.0.1 on 2025-10-08 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['-data_rilascio'], 'verbose_name': 'Software', 'verbose_name_plural': 'Software'},
        ),
        migrations.AddField(
            model_name='software',
            name='attivo',
            field=models.BooleanField(default=True, help_text='True se il software è ancora disponibile'),
        ),
        migrations.AddField(
            model_name='software',
            name='creato_il',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Data creazione record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='descrizione',
            field=models.TextField(blank=True, help_text='Descrizione del software (opzionale)'),
        ),
        migrations.AddField(
            model_name='software',
            name='modificato_il',
            field=models.DateTimeField(auto_now=True, help_text='Data ultima modifica'),
        ),
        migrations.AlterField(
            model_name='software',
            name='data_rilascio',
            field=models.DateField(help_text='Data di rilascio della versione'),
        ),
        migrations.AlterField(
            model_name='software',
            name='gratuito',
            field=models.BooleanField(default=False, help_text='True se il software è gratuito'),
        ),
        migrations.AlterField(
            model_name='software',
            name='nome',
            field=models.CharField(help_text='Nome del software', max_length=100),
        ),
        migrations.AlterField(
            model_name='software',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, help_text='Prezzo in euro (es: 239.88)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='software',
            name='versione',
            field=models.CharField(help_text='Versione del software (es: 1.0, 2.5.3)', max_length=20),
        ),
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome dell'azienda", max_length=200, unique=True)),
                ('partita_iva', models.CharField(help_text='Partita IVA (univoca)', max_length=20, unique=True)),
                ('sede', models.CharField(help_text='Indirizzo sede principale', max_length=200)),
                ('email', models.EmailField(help_text='Email di contatto aziendale', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Numero di telefono (opzionale)', max_length=20)),
                ('sito_web', models.URLField(blank=True, help_text='Sito web aziendale (opzionale)')),
                ('descrizione', models.TextField(blank=True, help_text="Descrizione dell'azienda")),
                ('data_fondazione', models.DateField(blank=True, help_text="Data di fondazione dell'azienda", null=True)),
                ('creata_il', models.DateTimeField(auto_now_add=True, help_text='Data creazione record')),
                ('modificata_il', models.DateTimeField(auto_now=True, help_text='Data ultima modifica')),
            ],
            options={
                'verbose_name': 'Azienda',
                'verbose_name_plural': 'Aziende',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='api_azienda_nome_c703e2_idx'), models.Index(fields=['partita_iva'], name='api_azienda_partita_5cae63_idx')],
            },
        ),
        migrations.AddField(
            model_name='software',
            name='azienda',
            field=models.ForeignKey(default=1, help_text='Azienda produttrice del software', on_delete=django.db.models.deletion.CASCADE, related_name='software', to='api.azienda'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='software',
            unique_together={('nome', 'versione', 'azienda')},
        ),
        migrations.AddIndex(
            model_name='software',
            index=models.Index(fields=['nome'], name='api_softwar_nome_efeffc_idx'),
        ),
        migrations.AddIndex(
            model_name='software',
            index=models.Index(fields=['azienda', 'data_rilascio'], name='api_softwar_azienda_703e69_idx'),
        ),
        migrations.RemoveField(
            model_name='software',
            name='produttore',
        ),
    ]
